- expected/orafce.out
- orafce--3.0.13.sql
- orafce-common.sql
- sql/orafce.sql
These functions were added to primarily address following incompatibilities:
* pg_catalog.lpad and pg_catalog.rpad remove the trailing blanks of CHAR arguments
* pg_catalog.lpad and pg_catalog.rpad consider character length, not display length, so add custom C implementations and redefine SQL functions to use the custom implmentations
But, my original commit did not make this very clear. So, I have rearranged and added comments so that it's more clear. It should be helpful for maintainability.
NOTE: Actually, there is no need to separately define functions for VARCHAR2 and NVARCHAR2 because they can safely use text versions. But, in case of PG 8.3, it causes conflict because (N)VARCHAR2 can be implicit cast to both CHAR and text, so there is errors like below:
``
ERROR:  function …
> Rearrange the changes LPAD, RPAD commit and add comments about incompatibilities

- README.asciidoc
The sub-title "VARCHAR2 and NVARCHAR2 Support" is misplaced due to broken markdown.
> Fix some markdown in REAME.asciidoc

- builtins.h
- charlen.c
- charpad.c
- msvc/orafce.2010.vcxproj
- nvarchar2.c
- orafce--3.0.13.sql
- orafce-common.sql
- varchar2.c
The msvc/orafce.2010.vcxproj file did not consider following files:
oraguc.c
charlen.c
charpad.c
nvarchar2.c
varchar2.c
Make related changes. Additionally mark various symbols with PGDLLEXPORT as appropriate.
Note: even with these changes, we need to rebuild PostgreSQL after marking two symbols days[] and session_timezone with PGDLLIMPORT. Otherwise there are errors like:
Compiler Error C2370 redefinition; different storage class
when building orafce.
By the way, I have used Microsoft Visual Studio Express 2013 with postgres built from postgresql-9.4.0.tar.gz.
> Fix Windows (MSVC) build for recently included files and related changes

- charlen.c
- charpad.c
- expected/dbms_pipe_session_A.out
- expected/dbms_pipe_session_B.out
- sql/dbms_pipe_session_A.sql
- sql/dbms_pipe_session_B.sql
Following fixes are needed for recent failures of regression tests
1) fix PG_FUNCTION_INFO_V1 declarations of lpad, rpad and bpcharlen that were recently renamed (this was reported on discussion group recently)
https://groups.google.com/d/msg/orafce-general/1OV9297FvDU/zHWqnLhRwS4J
2) I recently found that \set ECHO all; (with the trailing semicolon) causes following error:
+ unrecognized value "all;" for "ECHO"; assuming "none"
So, get rid of them in dbms_pipe regression test scripts. I also fixed some extraneous whitespace in the same commit.
> Fix recently discovered errors in regression tests

- Makefile
OS X requires all symbols in the module to be resolved at build time.
This requires -lintl if the build is NLS-enabled.  The previous code
only did this on Windows, but it's really appropriate for all
platforms.  The previous code for non-Windows didn't make sense.
> Fix NLS-enabled build on OS X

- utility.c
After being set here, start is overwritten in the eol case before being used again. In the non-eol case, the loop ends and start is no longer used. Remove the extraneous variable setting to reduce confusion.
Unless of course, I am confused =)
> Avoid setting unused variable value

- charpad.c
- expected/orafce.out
rpad() pads a half-width space at the end of line, not at the
beggining of line to satisfy the required output_width when it pads
multibyte characters.
> fix the position of a half-width space added by rpad().

- doc/sql_migration/sql_migration03.md
Function REGEXP_SUBSTR() doe not exists in PostgreSQL but it can be translated using the following rule.
Translation of `REGEX_SUBSTR( string, pattern, [pos], [nth])` can be converted into:
```
SELECT array_to_string(a, '')
FROM regexp_matches(substr(string, pos), pattern, 'g') AS foo(a)
LIMIT 1 OFFSET (nth - 1);
```
Optional fifth parameter of match_parameter is appended to 'g' when present.
> Translation of REGEXP_SUBSTR

- nvarchar2.c
- orafce--3.7.sql
- varchar2.c
pg_proc.protransform was renamed to pg_proc.prosupport.
Also, varchar_transform() was renamed to varchar_support().
- 1fb57af92069ee104c09e2016af9e0e620681be3
> Fix build for PostgreSQL 12

- .travis.yml
To notice breakage like in #103, I suggest running the testsuite on Travis. I enabled tests for PG 9.2+ because of one the NEWS items mentions that as supported; it might be worthwhile to add a note to README.asciidoc about which versions are supported.
https://travis-ci.org/github/credativ/orafce
Currently only PG11..13 are working.
Thanks for considering!
> Run the testsuite on travis-ci.org

- varchar2.c
Hello,
in funciton ```varchar2_input(const char *s, size_t len, int32 atttypmod)```
```c
if (atttypmod >= (int32) VARHDRSZ && len > maxlen)
if (len > maxlen)
ereport(ERROR,
(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
errmsg("input value length is %zd; too long for type varchar2(%zd)", len , maxlen)));
```
I found the inner condition 'len > maxlen' has been judged in outer condition 
'if (atttypmod >= (int32) VARHDRSZ && len > maxlen)'.
I think it can be removed and try to commit a patch to fix it.
> fix: 'if' condition is always true

- others.c
It seems ‘valtype’ is initialized twice, I try to remove Redundant initialization and variable.
> Remove redundant initialization

- orafce--3.6--3.7.sql
Hi
I found the bug when updating orafce from version 3.6 to newer version.
commit 9ed58cf fixes filter in oracle.user_tables view, but the bug remains
when updating orafce from 3.6 to newer version by
ALTER EXTENSION orafce UPDATE because orafce--3.6--3.7.sql does not have this fix.
This PR fix this. 
Regards,
Daisuke, Higuchi.
> Fix the wrong filter in oracle.user_tables view in orafce--3.6--3.7.sql.

- expected/dbms_random_1.out
On big-endian architectures, the dbms_random.string() output is
different. Allow regression tests to pass by adding an alternate _1.out
file.
https://buildd.debian.org/status/logs.php?pkg=orafce&ver=3.13.4-2
I did not investigate if it would be possible to tweak the code such that the output is the same on all architectures. That might be the better fix; my variant was the easier one.
> Catch dbms_random.string() output variation on big-endian

- doc/orafce_documentation/Orafce_Documentation_01.md
- doc/orafce_documentation/Orafce_Documentation_05.md
- expected/regexp_func.out
- orafce--3.14--3.15.sql
- orafce--3.15.sql
- sql/regexp_func.sql
This function supports start position and occurrence in addition to the PostgreSQL regexp_replace() implementation.
It correspond to the Oracle behavior and consist in plpgsql functions based on PostgreSQL regexp_matches() and
regexp_replace(). All details of the implementation is explained in the documentation. Also include in this patch also
include regression tests for regexp_replace() including the Oracle queries and results in comment.
Add raise exception when regexp modifiers are not supported by the Oracle implementation. Supported flags are:
- 'i' specifies case-insensitive matching.
- 'c' specifies case-sensitive matching.
- 'n' allows the period (.) to match the newline character.
- 'm' treats the source string as multiple lines.
- 's' alias for 'm' used by DB2 implementation of …
> Add Oracle regexp_replace() function

- Makefile
- doc/orafce_documentation/Orafce_Documentation_06.md
- expected/dbms_utility.out
- orafce.control
- sql/dbms_utility.sql
- utility.c
Add DBMS_UTILITY.GET_TIME function, it returns the current time in
100th's of a second from a point in time in the past. This function
is used for determining elapsed time. This function is widely used
in some Oracle installation for timing of functions or statements.
Example of use:
DO $$
DECLARE
start_time integer;
end_time integer;
BEGIN
start_time := DBMS_UTILITY.GET_TIME;
PERFORM pg_sleep(10);
end_time := DBMS_UTILITY.GET_TIME;
RAISE NOTICE 'Execution time: % seconds', (end_time - start_time)/100;
END
$$;
This function do not return the same value as the Oracle implementation
and the value is negative. But it is mainly used to get an elapsed time
between two execution of the function so this will give the right result.
> Implement function DBMS_UTILITY.GET_TIME the right way.

- sql/dbms_utility.sql
round() rounds down only up to 2.49, but on some build machines the test
needs more time. Use trunc() instead for more legroom up to 2.99.
> sql/dbms_utility.sql: Allow longer test runtime

- orafce--3.10--3.11.sql
Hi
I found the bug when updating orafce from version 3.9 to newer version.
orafce--3.11.sql deleted the REVOKE of utl_file.tmpdir(), 
but forgot to append GRANT in orafce--3.10--3.11.sql.
This PR fix this.
Regards,
Wei, Sun.
> Fix access privileges of utl_file.tmpdir()

- sqlscan.l
The commit 3788c66788 of PG had improved various places that double the size of a buffer.
This patch fixed the same problem in orafce.
> Improve the place that double the size of a buffer

- alert.c
The declaration of function find_and_remove_message_item is missing a space. It seems to be non-standard. Fix it.
> Fix a non-standard function declaration.

- expected/dbms_random_2.out
Hi
On Windows architectures, the dbms_random.string() output is
different. Allow regression tests to pass by adding an alternate _2.out
file.
I did not investigate if it would be possible to tweak the code such that the output is the same on all architectures. That might be the better fix; my variant was the easier one.
> Catch dbms_random.string() output variation on Windows

- README.asciidoc
Minor tweak to change "behave" to "behaviour" in order to make a sentence grammatically correct.
> Minor grammatical fix to README.asciidoc

- Makefile
- README.asciidoc
- doc/orafce_documentation/Orafce_Documentation_01.md
- doc/orafce_documentation/Orafce_Documentation_05.md
- expected/orafce.out
- orafce--3.17--3.18.sql
- orafce--3.18.sql
- orafce.control
- others.c
- sql/orafce.sql
Oracle functions LEAST and GREATEST return NULL if at least one of the parameters is NULL. This is not the case for the PostgreSQL equivalent functions which only return NULL when all the parameters are NULL. This patch creates the two functions in the oracle schema to have the same behavior than in Oracle.
The greatest and least functions are redefined in schema oracle using a C function. They are also SQL functions redefinition with two and three parameters of most common data type using the STRICT attribute so that most common call can be fast and inlined.
> Change behavior of the least() and greates() functions to return null on null input

- README.asciidoc
- file.c
- shmmc.c
Also in passing, remove whitespace at end of lines in the documentation.
> Fix typos and spelling in docs and error messages

- utility.c
get_time() converted microseconds since epoch to int32 and then divided by 10^4
to get centiseconds.  This computation gave a narrow range of [-214749, 214748]
that overflowed every 72 minutes or so.  Use int64 for intermediate values to
get the full range of int32 and make seeing an overflow less likely.
> Fix dbms_utility.get_time() to use the full range of int32.

- convert.c
The loop over the bytes of a string in to_single_byte() read the next byte to
check it's not zero before testing for the end of string.  But a string of type
text is not zero-terminated, so this loop read past the end of string.  Unlike
bytea, text cannot contain zero bytes, so just drop this check.
Found via Valgrind testing.
> Fix read past the end of string in to_sigle_byte().

- expected/nlssort.out
- expected/nlssort_1.out
- sql/nlssort.sql
This test fails on other systems because either the en_US.utf8 locale isn't
available or gives a different ordering.
This fixes #185.
> Limit nlssort test to Linux/glibc systems with en_US.utf8 installed.

- others.c
Before:
```
postgres=# select length(oracle.nlssort(repeat(repeat('x', 1000), 200000), 'en_US.UTF-8'));
server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
LOG:  server process (PID 76533) was terminated by signal 11: Segmentation fault: 11
```
After:
```
postgres=# select length(oracle.nlssort(repeat(repeat('x', 1000), 200000), 'en_US.UTF-8'));
ERROR:  invalid memory alloc request size 1600000009
```
> nlssort: Add a missing call to PG_RE_THROW.

- sql/nlssort.sql
For PG >= 15 explicitly set the locale provider libc when creating the database with SQL_ASCII encoding. Otherwise during installcheck the new database may use the ICU locale provider (from template0) which does not support this encoding.
Steps to reproduce:
1. Build orafce with PG >= 15.
2. Create a cluster for installcheck:
`initdb --locale-provider icu --icu-locale en-US -D data && pg_ctl -D data -l logfile start`
3. Run installcheck.
4. See regression.diffs:
```
diff -U3 /home/marina/orafce/expected/nlssort_1.out /home/marina/orafce/results/nlssort.out
--- /home/marina/orafce/expected/nlssort_1.out	2022-10-31 09:10:59.057911822 +0300
+++ /home/marina/orafce/results/nlssort.out	2022-10-31 09:41:31.636318864 +0300
@@ -6,3 +6,7 @@
AS skip_test \gset
\if :skip_test
\quit
+\endif
+\set …
```
> Fix database creation during installchecks for ICU cluster

- doc/sql_migration/sql_migration04.md
ERROR:  column reference "name" is ambiguous
> fix hierarchical query SQL

- doc/sql_migration/sql_migration04.md
CONNECT_BY_ROOT should be the root node of hierarchical query,  not the upper node of the current node.
> fix: CONNECT_BY_ROOT in hierarchical query is converted to WITH RECURSIVE syntax

- dbms_sql.c
A static analyzer found an error here - both conditions can't be true at the same time. It's probably just a typo so here's a fix
> Fix a condition to make code reachable

- Makefile
- expected/regexp_func.out
- orafce--4.8--4.9.sql
- orafce--4.9.sql
- orafce.control
- sql/regexp_func.sql
to have the same behavior than Oracle with newline characters and the use of dot in the pattern.
> Fix REGEXP_COUNT and REGEXP_SUBSTR functions

- expected/dbms_random_2.out
The commit 2ebb383 missed alternative outputs (dbms_random_2.out) for test dbms_random (windows)
> added an alternative output for test dbms_random (Windows)

- datefce.c
- expected/orafce.out
- orafce--4.12--4.13.sql
- orafce--4.13.sql
- orafce.c
- orafce.h
- sql/orafce.sql
This patch raise an error when Oracle's to_date() bugs are reached. This concern dates before 1582-10-05 ('J2299159') using the 'J' format and dates before 1100-03-01 that cannot be verified due to a bug in Oracle with other format.
Add orafce.oracle_compatibility_date_limit configuration variable to be able to disable this feature. Enabled by defaut.
> Raise an error when Oracle's to_date() bugs are reached.

- datefce.c
- expected/orafce.out
- sql/orafce.sql
With Oracle passing en empty string to the to_date(txt, fmt) function returns NULL whereas PostgreSQL returns '0001-01-01 BC'. This true whatever is the format passed as second argument.
PostgreSQL + orafce without the patch:
```
gilles=# SELECT oracle.to_date('', 'YYYY-MM-DD');
to_date    
---------------
0001-01-01 BC
(1 row)
```
Oracle
```
SQL> SELECT to_date('', 'J') FROM DUAL;
TO_DATE('
---------
```
This patch change the behavior of the function oracle.to_date(txt, fmt) to mimic Oracle.
```
gilles=# SELECT oracle.to_date('', 'YYYY-MM-DD');
to_date 
---------
(1 row)
```
> Force to_date(text,text) to return null with empty string

- orafce--4.13--4.14.sql
- orafce--4.14.sql
- orafce.control
Also increase version to 4.14
The use of to_date with an integer as first parameter is required when using the 'J' format.
Close #288
> Add support to nvl(double precision, integer) and to_date(integer, text)
